class HomeController < ApplicationController

  def index
    @orgaos = [ 'REFINANCIAMENTO DA DIVIDA PUBLICA MOBILIARIA FEDERAL', 'MINISTERIO DA PREVIDENCIA SOCIAL', 'ENCARGOS FINANCEIROS DA UNIAO', 'TRANSFERENCIAS A ESTADOS, DISTRITO FEDERAL E MUNICIPIOS', 'MINISTERIO DA SAUDE', 'MINISTERIO DA EDUCACAO', 'MINISTERIO DA DEFESA', 'MINISTERIO DO TRABALHO E EMPREGO', 'MINISTERIO DO DESENVOLVIMENTO SOCIAL E COMBATE À FOME', 'OPERACOES OFICIAIS DE CREDITO', 'MINISTERIO DAS CIDADES', 'MINISTERIO DA FAZENDA', 'MINISTERIO DOS TRANSPORTES', 'JUSTICA DO TRABALHO', 'MINISTERIO DO PLANEJAMENTO, ORCAMENTO E GESTAO', 'MINISTERIO DA JUSTICA', 'MINISTERIO DA INTEGRACAO NACIONAL', 'MINISTERIO DE MINAS E ENERGIA', 'MINISTERIO DA AGRICULTURA, PECUARIA E ABASTECIMENTO', 'MINISTERIO DA CIENCIA E TECNOLOGIA', 'RESERVA DE CONTINGENCIA', 'JUSTICA FEDERAL', 'MINISTERIO DO DESENVOLVIMENTO AGRARIO', 'MINISTERIO DAS COMUNICACOES', 'JUSTICA ELEITORAL', 'CAMARA DOS DEPUTADOS', 'PRESIDENCIA DA REPUBLICA', 'MINISTERIO DO MEIO AMBIENTE', 'MINISTERIO PUBLICO DA UNIAO', 'SENADO FEDERAL', 'MINISTERIO DA CULTURA', 'MINISTERIO DO TURISMO', 'MINISTERIO DO ESPORTE', 'MINISTERIO DO DESENVOLVIMENTO, INDUSTRIA E COMERCIO EXTERIOR', 'MINISTERIO DAS RELACOES EXTERIORES', 'PRESIDENCIA DA REPUBLICA', 'JUSTICA DO DISTRITO FEDERAL E DOS TERRITORIOS', 'TRIBUNAL DE CONTAS DA UNIAO', 'SECRETARIA DE PORTOS', 'SUPERIOR TRIBUNAL DE JUSTICA', 'CONTROLADORIA-GERAL DA UNIAO', 'MINISTERIO DA PESCA E AQÜICULTURA', 'SUPREMO TRIBUNAL FEDERAL', 'JUSTICA MILITAR DA UNIAO', 'SECRETARIA DE DIREITOS HUMANOS', 'CONSELHO NACIONAL DE JUSTICA', 'SECRETARIA DE POLITICAS PARA AS MULHERES', 'CONSELHO NACIONAL DO MINISTERIO PUBLICO', 'SECRETARIA DE POLITICAS DE PROMOCAO DA IGUALDADE RACIAL', 'SECRETARIA DE AVIACAO CIVIL', 'SECRETARIA DE ASSUNTOS ESTRATEGICOS', 'GABINETE DA VICE-PRESIDENCIA DA REPUBLICA', 'RECEITA DO TESOURO DA UNIAO', 'ADVOCACIA-GERAL DA UNIAO' ].sort
  end

  def profile
    @slug   = params[:orgao]
    @orgao  = params[:orgao].gsub("-", " ").titleize
    @ano    = params[:ano].to_i
  end

  def about
  end

  def who_we_are
  end

  def faq
  end

  def help
  end

  def contact
  end

end
